# Generated by Django 2.1.2 on 2018-10-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='manager_id',
            new_name='manager',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='departament_id',
            new_name='departament',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='departament_id',
            new_name='departament',
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
