# Generated by Django 2.1.2 on 2018-10-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0003_auto_20181025_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='product_id',
            new_name='product',
        ),
    ]
