# Generated by Django 2.1.2 on 2018-10-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0004_auto_20181025_0737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='name',
            new_name='departament_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='employee_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='product_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='departament',
            name='manager',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='employee',
            name='departament',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='departament',
            field=models.TextField(default=''),
        ),
    ]
