# Generated by Django 2.1.2 on 2018-10-25 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0005_auto_20181025_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departament',
            new_name='departament_name',
        ),
    ]
