# Generated by Django 2.1.2 on 2018-10-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0006_auto_20181025_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='manager',
        ),
        migrations.AddField(
            model_name='departament',
            name='manager_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompData.Employee'),
        ),
        migrations.AlterField(
            model_name='product',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompData.Departament'),
        ),
    ]
