# Generated by Django 2.1.2 on 2018-10-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0008_auto_20181025_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.TextField(default=''),
        ),
    ]
