# Generated by Django 2.1.2 on 2018-10-26 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0010_auto_20181026_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departament',
            name='manager_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employee_name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_name',
        ),
        migrations.AddField(
            model_name='departament',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompData.Employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product',
            field=models.TextField(default=''),
        ),
    ]
