# Generated by Django 2.1.2 on 2018-10-26 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0011_auto_20181026_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='departament_name',
            new_name='departament',
        ),
    ]
