# Generated by Django 2.1.2 on 2018-10-28 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0013_auto_20181028_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='departament',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CompData.Departament'),
        ),
    ]
