# Generated by Django 2.1.2 on 2018-10-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0014_product_departament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='departament',
            new_name='name',
        ),
    ]
