# Generated by Django 2.1.2 on 2018-10-29 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0015_auto_20181029_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product',
            new_name='name',
        ),
    ]
