# Generated by Django 2.1.2 on 2018-10-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CompData', '0017_auto_20181031_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departament',
            old_name='employee',
            new_name='manager',
        ),
    ]
